global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"

    scrape_interval: 15s
    scrape_timeout: 15s

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'main-service-metrics'
    static_configs:
      - targets: ['main-service:9090']